### ISSUE TITLE
Feature request: Second statistic - % vis flagged that were not 0 

### ISSUE THREAD

**Issue by jaythespacehound** [bmarcote/evn_support#1]
At present the % flagged in flag_weights.py doesn't take into account mixed bandwidth/stations dropping out.
Would be convenient to also have a statistic that only shows how many vis were flagged that were not already 0 (i.e. how much data was bad).

**Comment by bmarcote** [comment]
Done in version 1.4.

**Comment by bmarcote** [comment]
Done in version 1.4.
